services:
  - type: web
    name: qdrant
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    disk:
      name: qdrant-data
      mountPath: /qdrant/storage
      sizeGB: 1